model:
  params:
    history_encoder:
      checkpoint: /home/transaction-generation/log/generation/ready/age/detpp.ckpt
      name: DeTPP
      latent_encoder:
        name: GRU
        params:
          hidden_size: 386
          num_layers: 1
      autoencoder:
        name: BaselineAE
        params:
          cat_emb_dim: 88
          num_emb_dim: 109
          num_norm: true
          use_time: true
        pretrain: false
        frozen: True
        checkpoint: null
        batch_transforms:
          - RescaleTime:
              loc: 0
              scale: 0.0013698630136986301
      pooler: last
      params:
        k_factor: 1.0037504654857723