model:
  name: LatentDiffusionGenerator
  latent_encoder:
    name: ConditionalBridgeEncoder
    params:
      generation_len: ${data_conf.generation_len}
      reference_len: ${data_conf.generation_len} # not necessary, this attribute will be generated automatically
      num_classes: 1
      noise_schedule: ve #ve, vp, i2sb
      gen_sampler: dbim # heun, dbim, dbim_high_order
      sampling_nfe: 50