model:
  latent_encoder:
    params:
      denoiser_name: DiT # currently only DiT is supported
      hidden_size: 1152 ## must be the times of laten_size
      depth: 7
      num_heads: 16
      mlp_ratio: 4


optimizer:
  name: AdamW
  params:
    lr: 1.e-4
    betas:
     - 0.9
     - 0.999
    eps: 1e-8
    weight_decay: 1.e-2