model:
  latent_encoder:
    params:
      denoiser_name: DiT # currently only DiT is supported
      hidden_size: 1152 ## must be the times of laten_size
      depth: 7
      num_heads: 16
      mlp_ratio: 4


optimizer:
  name: AdamW
  params:
    lr: 1.e-3