evaluator:
  devices: ["cuda:0", "cuda:0"] # ALWAYS SET MORE THAN 1 DEVICE
  topk: 1
  temperature: 1.
  metrics:
    - OTD: {focus_on: ["<target_token>"], f1_average: micro}
    - OTD: {max_shift: 0, focus_on: ["<target_token>"], f1_average: micro}
    - Levenshtein
    - Cardinality