config_factory: [start, datasets/age/age, methods/tabsyn/base, metrics/with_detection/age]

trainer:
  ema:
    beta: 0.9999
    update_after_step: 10000
    update_every: 10

model:
  autoencoder:
    name: AR_VAE
    params:
      use_time: True
      num_layers: 3
      d_token: 32
      n_head: 8
      factor: 16
    pretrain: False
    frozen: True
    checkpoint: /home/transaction-generation/log/generation/ready/age/ar_vae_3.ckpt
    batch_transforms:
  latent_encoder:
    params:
      base_factor: 512 # unetXL

data_conf:
  train_resamples: 5
  batch_size: 128
  train_transforms:
    "0": null
    "1": null
    "log_tfs": null
    "vr_decimal":
      VariableRangeDecimal:
        names: ${data_conf.num_names}
        time_name: ${data_conf.time_name}


optimizer:
  name: AdamW
  params:
    lr: 1.e-3
    weight_decay: 1.e-2

schedulers:
  "step":
    StepLR:
      step_size: 20
      gamma: 0.2