# TabSyn++ with 
# - old vae autoencoder, 
# - default Unet1D (XL) denoiser architecture
# - repeat reference
# - (learnable) GRU history encoder

config_factory: [
  start, 
  datasets/age/age, 
  methods/ldm/train_defaults, 
  methods/ldm/ae/age/oldvae, # old vae on age as autoencoder 
  methods/ldm/nn/Unet1D, # Unet1D as denoiser
  methods/ldm/ref/repeat, # repeat reference
  methods/ldm/histemb/gru, # (learnable) GRU history encoder
  methods/ldm/tabsyn/base,
  metrics/with_detection/age,
]

model:
  latent_encoder:
    params:
      cfg_p_uncond: 0.2
      cfg_w: 1. # during training - it is better to set cfg_w = 1, set 2. to see how it works.