trainer:
  ckpt_track_metric: loss
  metrics_on_train: True
  total_iters: 10_000_000 # may be it is too much...
  ema:
    beta: 0.9999
    update_after_step: 10000
    update_every: 10

data_conf:
  train_resamples: 5
  batch_size: 128
  train_random_end: time
  train_transforms:
    "3":
      CutTargetSequence:
        target_len: ${data_conf.generation_len}

schedulers:
  "plate":
    ReduceLROnPlateau:
      factor: 0.1
      patience: 3
      threshold: 0.01

loss:
  name: DummyLoss