data_conf:
  train_resamples: 5
  batch_size: 128
  train_random_end: time
  train_transforms:
    "3":
      CutTargetSequence:
        target_len: 32
  
  
# MODEL
# Now it works oonly with one categorical in dataset!!!! 
# Please, provide correct params fix, diff, losses. If we wanna diff cats lets provide type_loss in losses.
# TODO: Fix this shit
model:
  params:
    fix_features: []
    diff_features: ["small_group", "trans_date", "amount_rur"]
    losses: ['type_loss', 'time_loss']
    cfg_w: 1.
    order_invariant_mode: False
    help_net:
      name: GroundTruthGenerator
      # checkpoint:
    